ALTER TYPE "DocumentAccessAuditEvent" ADD VALUE IF NOT EXISTS 'COMMENT_CREATED';
ALTER TYPE "DocumentAccessAuditEvent" ADD VALUE IF NOT EXISTS 'COMMENT_REPLIED';
ALTER TYPE "DocumentAccessAuditEvent" ADD VALUE IF NOT EXISTS 'COMMENT_RESOLVED';
