// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // ts-node runs seed.ts directly — no compiled .js needed
    // -r dotenv/config preloads .env before the seed subprocess runs
    seed: "npx ts-node -r dotenv/config prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
