ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'SIGNATURE_REVOKED';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'CERTIFICATE_REVOKED';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'CERTIFICATE_REISSUE_REQUESTED';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'CERTIFICATE_REQUEST_APPROVED';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'CERTIFICATE_REQUEST_REJECTED';
